In [77]:
import pandas as pd
file_path = r"/Volumes/Elements/跨境电商/TIKTOK/账务/全部 订单-2024-10-03.xlsx"
df = pd.read_excel(file_path)

In [78]:
df.shape
df=df.drop(index=0)
df

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Refund of seller co-funded voucher discount,Platform discounts,Refund of platform discounts,Platform co-funded voucher discounts,Refund of platform co-funded voucher discounts,Seller shipping fee discount,Estimated package weight (g),Actual package weight (g),Customer's bank for payment,Unnamed: 104
1,577279439921186015,To ship,Awaiting Shipment,NaN,Normal,1729707387210008366,NaN,Jam Tangan Kulit Wanita Fesyen Segi Empat Eleg...,Perak,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,577279313567777952,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,577279296075564066,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,577279245001328097,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,577279204170106774,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4912,576929695539627219,Completed,Completed,NaN,NaN,1729652629501937454,NaN,"Cincin Geometri, Mewah, Bersalut Emas 18K, den...","14092, Pembukaan Boleh Laras",1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,NaN,NaN
4913,576929671930938579,Completed,Completed,NaN,NaN,1729652577320797998,719,"Rantai Jam Tangan, Gaya Retro Chic Emas, denga...",lalai,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,NaN,NaN
4914,576929671926547667,Completed,Completed,NaN,NaN,1729651431281428270,NaN,"Pin Kerongsang, Rekaan Daun Bulatan Elegan, Pi...",Lingkaran Mutiara Cincin Emas,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,NaN,NaN
4915,576926169765610707,Canceled,Canceled,Cancel,NaN,1729650525646325550,NaN,"Cincin Jari, Bergaya dan Kreatif, Untuk Lelaki...",Tepung putih bulat kecil,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,576923325586965608,Completed,Completed,NaN,NaN,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0,NaN,NaN

In [8]:
"""指标	口径解释
已结算-成功付款	
Total settlement amount！= Nan&Cancelation/Return Type=空白&Total settlement amount>=0
已结算-派送问题付快递费（拒收/3次未送达退货商家）	
Total settlement amount！= Nan&Cancelation/Return Type=cancel&The order is cancelled by whom=system
已结算-达人样品	
Total settlement amount！= Nan&Cancelation/Return Type=空白&Total settlement amount<0
已结算-客户退款	
Total settlement amount！= Nan&Cancelation/Return Type=refund
已结算-取消订单	
Total settlement amount！= Nan&Cancelation/Return Type=cancel&The order is cancelled by whom!=system
未结算-取消（顾客取消，商家取消，系统取消-超时揽收，超时支付，派送问腿未退回商家）	
Total settlement amount= Nan&Current order status=canceled&completed
未结算-未揽收+派送中	
Total settlement amount= Nan&(Current order status=To ship|（Current order status=Shipped&Order Substatus=In Transit）)
未结算-已送达未达结算日期	
Total settlement amount= Nan&Current order status=Shipped&Order Substatus=Delivered
未结算-未支付（未达取消日期）	
Total settlement amount= Nan&Current Order Status=Unpaid
"""

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Refund of seller co-funded voucher discount,Platform discounts,Refund of platform discounts,Platform co-funded voucher discounts,Refund of platform co-funded voucher discounts,Seller shipping fee discount,Estimated package weight (g),Actual package weight (g),Customer's bank for payment,Unnamed: 104
1,577279439921186015,To ship,Awaiting Shipment,NaN,Normal,1729707387210008366,NaN,Jam Tangan Kulit Wanita Fesyen Segi Empat Eleg...,Perak,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,577279313567777952,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,577279296075564066,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,577279245001328097,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,577279204170106774,To ship,Awaiting Shipment,NaN,Normal,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4912,576929695539627219,Completed,Completed,NaN,NaN,1729652629501937454,NaN,"Cincin Geometri, Mewah, Bersalut Emas 18K, den...","14092, Pembukaan Boleh Laras",1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,NaN,NaN
4913,576929671930938579,Completed,Completed,NaN,NaN,1729652577320797998,719,"Rantai Jam Tangan, Gaya Retro Chic Emas, denga...",lalai,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,NaN,NaN
4914,576929671926547667,Completed,Completed,NaN,NaN,1729651431281428270,NaN,"Pin Kerongsang, Rekaan Daun Bulatan Elegan, Pi...",Lingkaran Mutiara Cincin Emas,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,NaN,NaN
4915,576926169765610707,Canceled,Canceled,Cancel,NaN,1729650525646325550,NaN,"Cincin Jari, Bergaya dan Kreatif, Untuk Lelaki...",Tepung putih bulat kecil,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,576923325586965608,Completed,Completed,NaN,NaN,1729646477933446958,NaN,"Jam Tangan Kuarza, Fesyen Elegan, Untuk Wanita...",lalai,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0,NaN,NaN

In [95]:
#已结算-成功付款	
#Total settlement amount！= Nan&Cancelation/Return Type=空白&Total settlement amount>=0
	
df_settled_success=df[(df["Total settlement amount"]>0.0000001) & (pd.isna(df['Cancelation/Return Type']))]
df_settled_success.shape
# >=0:3135 rows × 105 columns

#df[df["Total settlement amount"]>=0]["Total settlement amount"]
#df[pd.isna(df['Cancelation/Return Type'])]["Cancelation/Return Type"]

(3135, 105)

In [97]:
#已结算-成功付款
df_settled_success['SKU ID'].value_counts()
df_settled_success.groupby('SKU ID')['Total settlement amount'].sum()

SKU ID
1729646477933446958    36381.56
1729650525646194478       12.71
1729650525646325550        3.25
1729651429246535470        6.13
1729652579968517934       20.28
1729652579968583470       55.99
1729652579968714542       34.77
1729663368008206126       21.90
1729664281430624046        4.95
1729705158758008622      302.63
1729707387209942830     9141.19
1729707387210008366     2991.39
1729707514007095086       98.17
1729707514007160622       79.81
1729707636384040750       15.80
1729707696804235054       10.41
1729707696804300590       23.66
1729708427984144174       38.34
1729708427984209710       19.17
1729720111462844206       76.82
1729720111462909742      116.77
1729727685529536302       65.50
1729727685529601838       21.84
1729727685529667374       38.84
1729728478853695278       35.27
1729746655701731118       28.74
1729746792235108142       18.25
1729747278159120174       18.98
1729747278159185710       16.84
1729747278159251246       35.89
1729747278159316782       16.95
1729748094758848302       16.06
1729748094758913838       15.08
1729748094758979374       14.44
1729752876217304878     1101.21
1729755966770874158       31.64
Name: Total settlement amount, dtype: float64

In [48]:
#已结算-派送问题付快递费（拒收/3次未送达退货商家）
#Total settlement amount！= Nan&Cancelation/Return Type=cancel&The order is cancelled by whom=system
df_settled_dilivery_error=df[(pd.notna(df['Total settlement amount'])) & (df['Cancelation/Return Type']=="Cancel") &(df['Cancel By']=="System")]
df_settled_dilivery_error['Total settlement amount']
df_settled_dilivery_error.shape
# 47

(47, 105)

In [49]:
#已结算-达人样品	
#Total settlement amount！= Nan&Cancelation/Return Type=空白&Total settlement amount<0

df_settled_influncer_sample=df[(pd.notna(df['Total settlement amount'])) & (pd.isna(df['Cancelation/Return Type'])) &(df['Total settlement amount'] <0)]
df_settled_influncer_sample.shape
#

(145, 105)

In [51]:
#已结算-客户退款	
#Total settlement amount！= Nan&Cancelation/Return Type=refund
df_settled_customer_refund=df[(pd.notna(df['Total settlement amount'])) & (df['Cancelation/Return Type']== "Return/Refund")]
df_settled_customer_refund.shape

(18, 105)

In [54]:
#已结算-取消订单
#Total settlement amount！= Nan&Cancelation/Return Type=cancel&The order is cancelled by whom!=system
df_settled_customer_cancel=df[(pd.notna(df['Total settlement amount'])) & (df['Cancelation/Return Type']== "Cancel")&(df['Cancel By']!="System")]
df_settled_customer_cancel.shape

(9, 105)

In [55]:
#未结算-取消（顾客取消，商家取消，系统取消-超时揽收，超时支付，派送问腿未退回商家）	
#Total settlement amount= Nan&Order Status=canceled or completed
df_unsettled_canceled=df[(pd.isna(df['Total settlement amount'])) & ((df['Order Status']== "Canceled")|(df['Order Status']== "Completed"))]
df_unsettled_canceled.shape

(566, 105)

In [57]:
#未结算-未揽收+派送中	
#Total settlement amount= Nan&(Current order status=To ship|（Current order status=Shipped&Order Substatus=In Transit）)
df_unsettled_on_delivery=df[(pd.isna(df['Total settlement amount'])) & ((df['Order Status']== "To ship")|((df['Order Status']== "Shipped")&(df['Order Substatus']== "In Transit")))]
df_unsettled_on_delivery.shape

(668, 105)

In [62]:
#未结算-已送达未达结算日期	
#Total settlement amount= Nan&Current order status=Shipped&Order Substatus=Delivered
df_unsettled_date_not_reached =df[(pd.isna(df['Total settlement amount'])) & ((df['Order Status']== "Shipped")&(df['Order Substatus']== "Delivered"))]
df_unsettled_date_not_reached.shape

(328, 105)

In [63]:
#未结算-未支付（未达取消日期）	
#Total settlement amount= Nan&Current Order Status=Unpaid
df_unsettled_unpaid=df[(pd.isna(df['Total settlement amount'])) & (df['Order Substatus']== "Unpaid")]
df_unsettled_unpaid.shape

(0, 105)